name: Skillup_CI/CD

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: build docker image with latest code
        uses: docker/build-push-action@v1
          with:
            registry: 176.36.164.228:5000
            repository: eclizator/skillup_php
            tags: latest
            tag_with_sha: true
      - name: restart backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull localhost:5000/eclizator/skillup_php
            docker run -d -p 8888:80 --name php_backend localhost:5000/eclizator/skillup_php || docker restart php_backend
